name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: ./scripts/travis-ci-before-install-linux.sh bionic
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1
